exp_id: 002-Upscale_t2m
tigge_dir: /datadrive/tigge/32km/
tigge_vars: [total_precipitation, 2m_temperature]
mrms_dir: /datadrive/mrms/4km/RadarOnly_QPE_06H/
rq_fn: /datadrive/mrms/4km/RadarQuality.nc
save_dir: /datadrive/saved_models
epochs: 10
nres: 3
nf: 64
relu_out: False